### ISSUE TITLE
Duck base version not explained 

### ISSUE THREAD

**Issue by ashish-chopra** [raul1991/DesignPatterns#3]
In strategy pattern, README file does not explain what ducksimulation app is about. What already exists in duck app as per design point. Then reading about the changes Bd modification proposed are fruitful to understand.

**Comment by raul1991** [comment]
Closing this issue with this [commit](https://github.com/raul1991/DesignPatterns/commit/5d43f54cad7d99b6908a0fdb797a09c189415d2e)
